### ISSUE TITLE
asking for resource

### ISSUE THREAD

**Issue by lewis56654281** [datawhalechina/llms-from-scratch-cn#20]
I am a student from HUST university, and I couldn't help reading the folling chapters even not translated, could you send me the English version of the book?  please contact me through 2408859305@qq.com

**Comment by Ethan-Chen-plus** [comment]
Hello!

Thank you for your interest in our code repository. Regarding the chapter translation you mentioned, you can find the relevant information in our Wiki: [Wiki Link](https://github.com/datawhalechina/llms-from-scratch-cn/wiki). The chapter has been mostly translated, and you can access it through this link: [Translated Chapter](https://github.com/datawhalechina/llms-from-scratch-cn/tree/main/Translated_Book).

If you have any questions while reading or need further assistance, please don’t hesitate to reach out.
